### ISSUE TITLE
Quotes from the guests/speakers

### ISSUE THREAD

**Issue by elliezub** [TheTechCommute/TheTechCommute#15]
Feature request: 
A carousel component with quotes from some of the guests/speakers, or just a collage of bubbles with the quotes and a picture of the person who said it (maybe also their social links??) 

You can assign this to me, and I will put some fake quotes temporarily. Maybe will use Daisy UI? 
If you like the idea, just lmk where you would like to see this, below the spotify iframe? or where?

**Comment by jasonetorres** [comment]
you have any updates on this @elliezub maybe a few screen grabs? also I asked @arcadejacob about maybe doing a stream in the discord perhaps we can do this?

**Comment by elliezub** [comment]
Hey @jasonetorres, I've got the basic structure, but probably need some quotes and pictures of actual speakers so it isn't full of the fake quotes. We could definitely do a stream about it though since there are some things that could be changed.

**Comment by jasonetorres** [comment]
hey @elliezub what do you need from us to get this going again

**Comment by elliezub** [comment]
Hey @jasonetorres I need some pictures and quotes, maybe about 6 to start so it doesn't look empty 🤔 

But the more the merrier
