### ISSUE TITLE
feat: add dark & light mode

### ISSUE THREAD

**Issue by CBID2** [TheTechCommute/TheTechCommute#23]
## Suggestion
It'd be awesome for people to have a way people to view the website without straining their eyesight. 
## Describe the solution you'd like

Adding a dark/light mode toggle 

## Describe alternatives you've considered
N/A.

 ## Additional context
N/A

**Comment by jasonetorres** [comment]
id love to see this happen, if anyone is interested. @CBID2 any thoughts

**Comment by Vijaykv5** [comment]
@CBID2 If you're not yet done, please let me know.
I'm up for it!

**Comment by CBID2** [comment]
I'm going to work on this @Vijaykv5

**Comment by swarupsahu08** [comment]
Hey @jasonetorres Can you assign me this issue ,I am interested to work on this issue

**Comment by CBID2** [comment]
> Hey @jasonetorres Can you assign me this issue ,I am interested to work on this issue

There’s already a PR for this issue. I highly recommend looking at other ones
