### ISSUE TITLE
Contributing Docs Readme isn't formatted correctly!

### ISSUE THREAD

**Issue by devarshishimpi** [TheTechCommute/TheTechCommute#25]
![Screenshot by Dropbox Capture](https://github.com/TheTechCommute/TheTechCommute/assets/43378923/b8f81376-4836-49b4-99e7-8024a26a65d7)
![Screenshot by Dropbox Capture](https://github.com/TheTechCommute/TheTechCommute/assets/43378923/d2ea41a2-a763-44aa-a56c-1fd0de1e8db8)

Readme isn't formatted correctly.

**Comment by jasonetorres** [comment]
These are great @devarshishimpi
