### ISSUE TITLE
[BUG](accessibility): footer text html tag 

### ISSUE THREAD

**Issue by ryandotfurrer** [TheTechCommute/TheTechCommute#32]
**Describe the bug**
The footer text is an `h4.` Semantically this does not make sense and it means headings are not in sequentially-descending order. 

**Expected behavior**
I would expect the footer text to be a simple `<p>` tag, _however_, if you'd like to keep it as a heading, make it an `h2`.

**Comment by rajneesh-18** [comment]
assign this to me

**Comment by rajneesh-18** [comment]
Assign it to me
