### ISSUE TITLE
Create a Template for Issues

### ISSUE THREAD

**Issue by chris-nowicki** [TheTechCommute/TheTechCommute#4]
I would like to create a template for the issues submissions.

**Comment by jasonetorres** [comment]
Would like to revisit this do you have the template MD built?

**Comment by chris-nowicki** [comment]
Not yet! Totally dropped the ball on this! I can complete this by end of day tomorrow :).  Dow that work?

**Comment by CBID2** [comment]
Hey @chris-nowicki. Are you still able to work on this? I can do this if you can't.

**Comment by chris-nowicki** [comment]
> Hey @chris-nowicki. Are you still able to work on this? I can do this if you can't.

Hey hey @CBID2! Go ahead and take this issue, I appreciate it! :).
