### ISSUE TITLE
[DOCS]: new PR template

### ISSUE THREAD

**Issue by jasonetorres** [TheTechCommute/TheTechCommute#45]
## Description
needs to have a formal template for PR submission

**Comment by G0v1ndD3v** [comment]
Hi, I’m interested in taking on this task. @choir241, I noticed you’ve been assigned to the issue. If you need help, I’d be happy to assist or pick this up.

**Comment by choir241** [comment]
Thanks @G0v1ndD3v, I'll let you know if I need any help, but I think I got it! Appreciate the sentiment though~
