### ISSUE TITLE
[DOCS]: HACKTOBERFEST readme 

### ISSUE THREAD

**Issue by jasonetorres** [TheTechCommute/TheTechCommute#46]
## Description

would like to have a formal doc showing the process for PR submission for hacktoberfest

**Comment by 2MJ-DEV** [comment]
I suggest we start on it.

**Comment by choir241** [comment]
@2MJ-DEV on it! ^^

**Comment by 2MJ-DEV** [comment]
@choir241  yes but that you can assign me this task

**Comment by 2MJ-DEV** [comment]
@choir241 Okay, that's fine.
