### ISSUE TITLE
[FIX]: Add margin to the footer text

### ISSUE THREAD

**Issue by michaella23** [TheTechCommute/TheTechCommute#60]
The footer text is flush with the bottom of the screen. Add some space under the text.

**Comment by programmerraja** [comment]
@michaella23  can i work this

**Comment by TechGeekRahul** [comment]
hey @michaella23  I want to work on this issue.can you assign it to me ?

**Comment by NOMADE55** [comment]
@michaella23 My PR (#64) even though a chunky one, fixes the issue. Let me know if something else is needd
