### ISSUE TITLE
Making the Front Page more Attractive

### ISSUE THREAD

**Issue by RithwikBejadi** [TheTechCommute/TheTechCommute#68]
The font style and the attributes of front page doesnt look attractive

I would like to work on this using internal CSS.

Please Assign this to me under Hactoberfest

**Comment by RithwikBejadi** [comment]
Please assign this to me under hacktoberfest, I would like to work on it

**Comment by michaella23** [comment]
Hello @RithwikBejadi, we have some changes to the UI coming soon in another PR. Once those changes are merged, you should take a look. Then, it would be great if you could describe some specific enhancements that you would like to see. Thank you.
